[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialMobilityAnalyzers = "050a7be8-18f9-52d6-bdba-0a194485d082"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
InspectDR = "d0351b0e-4b05-5898-87b3-e2a8edfddd1d"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LabjackU6Library = "13a5dcd1-fa46-5f5c-a4e8-ed6ffcaaca62"
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"
